//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类AgrProduceAnniversaryService 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class AgrProduceAnniversaryService : Entity 
	{
		public AgrProduceAnniversaryService():base("AgrProduceAnniversaryService") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _SysAreaSerialnum;
		private string _AgrProductObjectSerialnum;
		private int _Month;
		private string _Ten;
		private string _MainDevelopmentalStage;
		private string _PossibleDisasters;
		private string _ServiceFocus;
		private string _ServiceContent;
		private string _TakeMeasures;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 区域编码
		/// </summary>
		public string SysAreaSerialnum
		{
			get{ return _SysAreaSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysAreaSerialnum,_SysAreaSerialnum,value);
				this._SysAreaSerialnum=value;
			}
		}
		/// <summary>
		/// 品种编码
		/// </summary>
		public string AgrProductObjectSerialnum
		{
			get{ return _AgrProductObjectSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.AgrProductObjectSerialnum,_AgrProductObjectSerialnum,value);
				this._AgrProductObjectSerialnum=value;
			}
		}
		/// <summary>
		/// 月
		/// </summary>
		public int Month
		{
			get{ return _Month; }
			set
			{
				this.OnPropertyValueChange(_.Month,_Month,value);
				this._Month=value;
			}
		}
		/// <summary>
		/// 旬号。上旬、中旬、下旬
		/// </summary>
		public string Ten
		{
			get{ return _Ten; }
			set
			{
				this.OnPropertyValueChange(_.Ten,_Ten,value);
				this._Ten=value;
			}
		}
		/// <summary>
		/// 主要作物发育期
		/// </summary>
		public string MainDevelopmentalStage
		{
			get{ return _MainDevelopmentalStage; }
			set
			{
				this.OnPropertyValueChange(_.MainDevelopmentalStage,_MainDevelopmentalStage,value);
				this._MainDevelopmentalStage=value;
			}
		}
		/// <summary>
		/// 可能出现的灾害
		/// </summary>
		public string PossibleDisasters
		{
			get{ return _PossibleDisasters; }
			set
			{
				this.OnPropertyValueChange(_.PossibleDisasters,_PossibleDisasters,value);
				this._PossibleDisasters=value;
			}
		}
		/// <summary>
		/// 服务重点
		/// </summary>
		public string ServiceFocus
		{
			get{ return _ServiceFocus; }
			set
			{
				this.OnPropertyValueChange(_.ServiceFocus,_ServiceFocus,value);
				this._ServiceFocus=value;
			}
		}
		/// <summary>
		/// 服务内容
		/// </summary>
		public string ServiceContent
		{
			get{ return _ServiceContent; }
			set
			{
				this.OnPropertyValueChange(_.ServiceContent,_ServiceContent,value);
				this._ServiceContent=value;
			}
		}
		/// <summary>
		/// 相应对策
		/// </summary>
		public string TakeMeasures
		{
			get{ return _TakeMeasures; }
			set
			{
				this.OnPropertyValueChange(_.TakeMeasures,_TakeMeasures,value);
				this._TakeMeasures=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.SysAreaSerialnum,
				_.AgrProductObjectSerialnum,
				_.Month,
				_.Ten,
				_.MainDevelopmentalStage,
				_.PossibleDisasters,
				_.ServiceFocus,
				_.ServiceContent,
				_.TakeMeasures,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._SysAreaSerialnum,
				this._AgrProductObjectSerialnum,
				this._Month,
				this._Ten,
				this._MainDevelopmentalStage,
				this._PossibleDisasters,
				this._ServiceFocus,
				this._ServiceContent,
				this._TakeMeasures,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._SysAreaSerialnum = DataUtils.ConvertValue<string>(reader["SysAreaSerialnum"]);
			this._AgrProductObjectSerialnum = DataUtils.ConvertValue<string>(reader["AgrProductObjectSerialnum"]);
			this._Month = DataUtils.ConvertValue<int>(reader["Month"]);
			this._Ten = DataUtils.ConvertValue<string>(reader["Ten"]);
			this._MainDevelopmentalStage = DataUtils.ConvertValue<string>(reader["MainDevelopmentalStage"]);
			this._PossibleDisasters = DataUtils.ConvertValue<string>(reader["PossibleDisasters"]);
			this._ServiceFocus = DataUtils.ConvertValue<string>(reader["ServiceFocus"]);
			this._ServiceContent = DataUtils.ConvertValue<string>(reader["ServiceContent"]);
			this._TakeMeasures = DataUtils.ConvertValue<string>(reader["TakeMeasures"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._SysAreaSerialnum = DataUtils.ConvertValue<string>(row["SysAreaSerialnum"]);
			this._AgrProductObjectSerialnum = DataUtils.ConvertValue<string>(row["AgrProductObjectSerialnum"]);
			this._Month = DataUtils.ConvertValue<int>(row["Month"]);
			this._Ten = DataUtils.ConvertValue<string>(row["Ten"]);
			this._MainDevelopmentalStage = DataUtils.ConvertValue<string>(row["MainDevelopmentalStage"]);
			this._PossibleDisasters = DataUtils.ConvertValue<string>(row["PossibleDisasters"]);
			this._ServiceFocus = DataUtils.ConvertValue<string>(row["ServiceFocus"]);
			this._ServiceContent = DataUtils.ConvertValue<string>(row["ServiceContent"]);
			this._TakeMeasures = DataUtils.ConvertValue<string>(row["TakeMeasures"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","AgrProduceAnniversaryService");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","AgrProduceAnniversaryService","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","AgrProduceAnniversaryService","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","AgrProduceAnniversaryService","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","AgrProduceAnniversaryService","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","AgrProduceAnniversaryService","更新用户");
			/// <summary>
			/// 区域编码
			/// </summary>
			public readonly static Field SysAreaSerialnum = new Field("SysAreaSerialnum","AgrProduceAnniversaryService","区域编码");
			/// <summary>
			/// 品种编码
			/// </summary>
			public readonly static Field AgrProductObjectSerialnum = new Field("AgrProductObjectSerialnum","AgrProduceAnniversaryService","品种编码");
			/// <summary>
			/// 月
			/// </summary>
			public readonly static Field Month = new Field("Month","AgrProduceAnniversaryService","月");
			/// <summary>
			/// 旬号。上旬、中旬、下旬
			/// </summary>
			public readonly static Field Ten = new Field("Ten","AgrProduceAnniversaryService","旬号。上旬、中旬、下旬");
			/// <summary>
			/// 主要作物发育期
			/// </summary>
			public readonly static Field MainDevelopmentalStage = new Field("MainDevelopmentalStage","AgrProduceAnniversaryService","主要作物发育期");
			/// <summary>
			/// 可能出现的灾害
			/// </summary>
			public readonly static Field PossibleDisasters = new Field("PossibleDisasters","AgrProduceAnniversaryService","可能出现的灾害");
			/// <summary>
			/// 服务重点
			/// </summary>
			public readonly static Field ServiceFocus = new Field("ServiceFocus","AgrProduceAnniversaryService","服务重点");
			/// <summary>
			/// 服务内容
			/// </summary>
			public readonly static Field ServiceContent = new Field("ServiceContent","AgrProduceAnniversaryService","服务内容");
			/// <summary>
			/// 相应对策
			/// </summary>
			public readonly static Field TakeMeasures = new Field("TakeMeasures","AgrProduceAnniversaryService","相应对策");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","AgrProduceAnniversaryService","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","AgrProduceAnniversaryService","备注");
		}
		#endregion


	}
}

