//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类ArticleContent 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class ArticleContent : Entity 
	{
		public ArticleContent():base("ArticleContent") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private string _CreateSysUserUserName;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _UpdateSysUserUserName;
		private string _Title;
		private string _ArticleCategorySerialnum;
		private string _ArticleCategoryName;
		private int? _Sort;
		private string _Remark;
		private int? _Views;
		private string _SourceName;
		private string _SourceUrl;
		private string _Cover;
		private DateTime? _PublishTime;
		private string _Content;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserUserName
		{
			get{ return _CreateSysUserUserName; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserUserName,_CreateSysUserUserName,value);
				this._CreateSysUserUserName=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserUserName
		{
			get{ return _UpdateSysUserUserName; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserUserName,_UpdateSysUserUserName,value);
				this._UpdateSysUserUserName=value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 分类
		/// </summary>
		public string ArticleCategorySerialnum
		{
			get{ return _ArticleCategorySerialnum; }
			set
			{
				this.OnPropertyValueChange(_.ArticleCategorySerialnum,_ArticleCategorySerialnum,value);
				this._ArticleCategorySerialnum=value;
			}
		}
		/// <summary>
		/// 分类名称
		/// </summary>
		public string ArticleCategoryName
		{
			get{ return _ArticleCategoryName; }
			set
			{
				this.OnPropertyValueChange(_.ArticleCategoryName,_ArticleCategoryName,value);
				this._ArticleCategoryName=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int? Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		/// <summary>
		/// 访问量
		/// </summary>
		public int? Views
		{
			get{ return _Views; }
			set
			{
				this.OnPropertyValueChange(_.Views,_Views,value);
				this._Views=value;
			}
		}
		/// <summary>
		/// 来源名称
		/// </summary>
		public string SourceName
		{
			get{ return _SourceName; }
			set
			{
				this.OnPropertyValueChange(_.SourceName,_SourceName,value);
				this._SourceName=value;
			}
		}
		/// <summary>
		/// 来源地址
		/// </summary>
		public string SourceUrl
		{
			get{ return _SourceUrl; }
			set
			{
				this.OnPropertyValueChange(_.SourceUrl,_SourceUrl,value);
				this._SourceUrl=value;
			}
		}
		/// <summary>
		/// 封面
		/// </summary>
		public string Cover
		{
			get{ return _Cover; }
			set
			{
				this.OnPropertyValueChange(_.Cover,_Cover,value);
				this._Cover=value;
			}
		}
		/// <summary>
		/// 发布时间
		/// </summary>
		public DateTime? PublishTime
		{
			get{ return _PublishTime; }
			set
			{
				this.OnPropertyValueChange(_.PublishTime,_PublishTime,value);
				this._PublishTime=value;
			}
		}
		/// <summary>
		/// 内容
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.CreateSysUserUserName,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.UpdateSysUserUserName,
				_.Title,
				_.ArticleCategorySerialnum,
				_.ArticleCategoryName,
				_.Sort,
				_.Remark,
				_.Views,
				_.SourceName,
				_.SourceUrl,
				_.Cover,
				_.PublishTime,
				_.Content};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._CreateSysUserUserName,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._UpdateSysUserUserName,
				this._Title,
				this._ArticleCategorySerialnum,
				this._ArticleCategoryName,
				this._Sort,
				this._Remark,
				this._Views,
				this._SourceName,
				this._SourceUrl,
				this._Cover,
				this._PublishTime,
				this._Content};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._CreateSysUserUserName = DataUtils.ConvertValue<string>(reader["CreateSysUserUserName"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._UpdateSysUserUserName = DataUtils.ConvertValue<string>(reader["UpdateSysUserUserName"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._ArticleCategorySerialnum = DataUtils.ConvertValue<string>(reader["ArticleCategorySerialnum"]);
			this._ArticleCategoryName = DataUtils.ConvertValue<string>(reader["ArticleCategoryName"]);
			this._Sort = DataUtils.ConvertValue<int?>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
			this._Views = DataUtils.ConvertValue<int?>(reader["Views"]);
			this._SourceName = DataUtils.ConvertValue<string>(reader["SourceName"]);
			this._SourceUrl = DataUtils.ConvertValue<string>(reader["SourceUrl"]);
			this._Cover = DataUtils.ConvertValue<string>(reader["Cover"]);
			this._PublishTime = DataUtils.ConvertValue<DateTime?>(reader["PublishTime"]);
			this._Content = DataUtils.ConvertValue<string>(reader["Content"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._CreateSysUserUserName = DataUtils.ConvertValue<string>(row["CreateSysUserUserName"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._UpdateSysUserUserName = DataUtils.ConvertValue<string>(row["UpdateSysUserUserName"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._ArticleCategorySerialnum = DataUtils.ConvertValue<string>(row["ArticleCategorySerialnum"]);
			this._ArticleCategoryName = DataUtils.ConvertValue<string>(row["ArticleCategoryName"]);
			this._Sort = DataUtils.ConvertValue<int?>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
			this._Views = DataUtils.ConvertValue<int?>(row["Views"]);
			this._SourceName = DataUtils.ConvertValue<string>(row["SourceName"]);
			this._SourceUrl = DataUtils.ConvertValue<string>(row["SourceUrl"]);
			this._Cover = DataUtils.ConvertValue<string>(row["Cover"]);
			this._PublishTime = DataUtils.ConvertValue<DateTime?>(row["PublishTime"]);
			this._Content = DataUtils.ConvertValue<string>(row["Content"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","ArticleContent");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","ArticleContent","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","ArticleContent","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","ArticleContent","创建用户");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserUserName = new Field("CreateSysUserUserName","ArticleContent","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","ArticleContent","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","ArticleContent","更新用户");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserUserName = new Field("UpdateSysUserUserName","ArticleContent","更新用户");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title","ArticleContent","标题");
			/// <summary>
			/// 分类
			/// </summary>
			public readonly static Field ArticleCategorySerialnum = new Field("ArticleCategorySerialnum","ArticleContent","分类");
			/// <summary>
			/// 分类名称
			/// </summary>
			public readonly static Field ArticleCategoryName = new Field("ArticleCategoryName","ArticleContent","分类名称");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","ArticleContent","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","ArticleContent","备注");
			/// <summary>
			/// 访问量
			/// </summary>
			public readonly static Field Views = new Field("Views","ArticleContent","访问量");
			/// <summary>
			/// 来源名称
			/// </summary>
			public readonly static Field SourceName = new Field("SourceName","ArticleContent","来源名称");
			/// <summary>
			/// 来源地址
			/// </summary>
			public readonly static Field SourceUrl = new Field("SourceUrl","ArticleContent","来源地址");
			/// <summary>
			/// 封面
			/// </summary>
			public readonly static Field Cover = new Field("Cover","ArticleContent","封面");
			/// <summary>
			/// 发布时间
			/// </summary>
			public readonly static Field PublishTime = new Field("PublishTime","ArticleContent","发布时间");
			/// <summary>
			/// 内容
			/// </summary>
			public readonly static Field Content = new Field("Content","ArticleContent","内容");
		}
		#endregion


	}
}

