//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类CHANNEL_MAP 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class CHANNEL_MAP : Entity 
	{
		public CHANNEL_MAP():base("CHANNEL_MAP") {}

		#region Model
		private decimal _CHANNEL_ID;
		private decimal _CONTENT_ID;
		/// <summary>
		/// 
		/// </summary>
		public decimal CHANNEL_ID
		{
			get{ return _CHANNEL_ID; }
			set
			{
				this.OnPropertyValueChange(_.CHANNEL_ID,_CHANNEL_ID,value);
				this._CHANNEL_ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal CONTENT_ID
		{
			get{ return _CONTENT_ID; }
			set
			{
				this.OnPropertyValueChange(_.CONTENT_ID,_CONTENT_ID,value);
				this._CONTENT_ID=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.CHANNEL_ID,
				_.CONTENT_ID};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._CHANNEL_ID,
				this._CONTENT_ID};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._CHANNEL_ID = DataUtils.ConvertValue<decimal>(reader["CHANNEL_ID"]);
			this._CONTENT_ID = DataUtils.ConvertValue<decimal>(reader["CONTENT_ID"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._CHANNEL_ID = DataUtils.ConvertValue<decimal>(row["CHANNEL_ID"]);
			this._CONTENT_ID = DataUtils.ConvertValue<decimal>(row["CONTENT_ID"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CHANNEL_MAP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CHANNEL_ID = new Field("CHANNEL_ID","CHANNEL_MAP","CHANNEL_ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CONTENT_ID = new Field("CONTENT_ID","CHANNEL_MAP","CONTENT_ID");
		}
		#endregion


	}
}

