//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类CompanyUser 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class CompanyUser : Entity 
	{
		public CompanyUser():base("CompanyUser") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _SysUserSerialnum;
		private string _CompanySerialnum;
		private string _FarmSerialnum;
		private string _FacilitySerialnum;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 用户编码
		/// </summary>
		public string SysUserSerialnum
		{
			get{ return _SysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysUserSerialnum,_SysUserSerialnum,value);
				this._SysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 企业编码
		/// </summary>
		public string CompanySerialnum
		{
			get{ return _CompanySerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CompanySerialnum,_CompanySerialnum,value);
				this._CompanySerialnum=value;
			}
		}
		/// <summary>
		/// 基地编码
		/// </summary>
		public string FarmSerialnum
		{
			get{ return _FarmSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.FarmSerialnum,_FarmSerialnum,value);
				this._FarmSerialnum=value;
			}
		}
		/// <summary>
		/// 设施编码
		/// </summary>
		public string FacilitySerialnum
		{
			get{ return _FacilitySerialnum; }
			set
			{
				this.OnPropertyValueChange(_.FacilitySerialnum,_FacilitySerialnum,value);
				this._FacilitySerialnum=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.SysUserSerialnum,
				_.CompanySerialnum,
				_.FarmSerialnum,
				_.FacilitySerialnum,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._SysUserSerialnum,
				this._CompanySerialnum,
				this._FarmSerialnum,
				this._FacilitySerialnum,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._SysUserSerialnum = DataUtils.ConvertValue<string>(reader["SysUserSerialnum"]);
			this._CompanySerialnum = DataUtils.ConvertValue<string>(reader["CompanySerialnum"]);
			this._FarmSerialnum = DataUtils.ConvertValue<string>(reader["FarmSerialnum"]);
			this._FacilitySerialnum = DataUtils.ConvertValue<string>(reader["FacilitySerialnum"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._SysUserSerialnum = DataUtils.ConvertValue<string>(row["SysUserSerialnum"]);
			this._CompanySerialnum = DataUtils.ConvertValue<string>(row["CompanySerialnum"]);
			this._FarmSerialnum = DataUtils.ConvertValue<string>(row["FarmSerialnum"]);
			this._FacilitySerialnum = DataUtils.ConvertValue<string>(row["FacilitySerialnum"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CompanyUser");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","CompanyUser","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","CompanyUser","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","CompanyUser","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","CompanyUser","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","CompanyUser","更新用户");
			/// <summary>
			/// 用户编码
			/// </summary>
			public readonly static Field SysUserSerialnum = new Field("SysUserSerialnum","CompanyUser","用户编码");
			/// <summary>
			/// 企业编码
			/// </summary>
			public readonly static Field CompanySerialnum = new Field("CompanySerialnum","CompanyUser","企业编码");
			/// <summary>
			/// 基地编码
			/// </summary>
			public readonly static Field FarmSerialnum = new Field("FarmSerialnum","CompanyUser","基地编码");
			/// <summary>
			/// 设施编码
			/// </summary>
			public readonly static Field FacilitySerialnum = new Field("FacilitySerialnum","CompanyUser","设施编码");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","CompanyUser","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","CompanyUser","备注");
		}
		#endregion


	}
}

