//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类CONTENT_LIST 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class CONTENT_LIST : Entity 
	{
		public CONTENT_LIST():base("CONTENT_LIST") {}

		#region Model
		private decimal _ID;
		private string _TITLE;
		private string _LONGTITLE;
		private decimal? _INFOTYPE;
		private decimal? _ORDERID;
		private string _INFOSOURCE;
		private string _KEYWORD;
		private DateTime? _TIME_PUBLISH;
		private DateTime? _TIME_UNPUBLISH;
		private string _SUMMARY;
		private bool? _PROP_TOP;
		private bool? _PROP_PIC;
		private string _HTML_PATH;
		private string _URL_LINK;
		private string _RELATION_ID;
		private string _HOT_ID;
		private string _TITLE_COLOR;
		private decimal? _STATE;
		private decimal? _Click;
		private string _PIC;
		private string _INFO_ID;
		private DateTime? _TIME_LAST;
		private decimal? _USER_ID;
		private string _USER_NAME;
		private decimal? _USER_ID_PUB;
		private string _USER_NAME_PUB;
		private string _MP3;
		private bool? _IPTV;
		private string _FLV;
		private bool? _PROP_INDEX;
		private string _City;
		private string _CustomType;
		private string _FileUser;
		private string _FileCode;
		/// <summary>
		/// 
		/// </summary>
		public decimal ID
		{
			get{ return _ID; }
			set
			{
				this.OnPropertyValueChange(_.ID,_ID,value);
				this._ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TITLE
		{
			get{ return _TITLE; }
			set
			{
				this.OnPropertyValueChange(_.TITLE,_TITLE,value);
				this._TITLE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string LONGTITLE
		{
			get{ return _LONGTITLE; }
			set
			{
				this.OnPropertyValueChange(_.LONGTITLE,_LONGTITLE,value);
				this._LONGTITLE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? INFOTYPE
		{
			get{ return _INFOTYPE; }
			set
			{
				this.OnPropertyValueChange(_.INFOTYPE,_INFOTYPE,value);
				this._INFOTYPE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? ORDERID
		{
			get{ return _ORDERID; }
			set
			{
				this.OnPropertyValueChange(_.ORDERID,_ORDERID,value);
				this._ORDERID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string INFOSOURCE
		{
			get{ return _INFOSOURCE; }
			set
			{
				this.OnPropertyValueChange(_.INFOSOURCE,_INFOSOURCE,value);
				this._INFOSOURCE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string KEYWORD
		{
			get{ return _KEYWORD; }
			set
			{
				this.OnPropertyValueChange(_.KEYWORD,_KEYWORD,value);
				this._KEYWORD=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TIME_PUBLISH
		{
			get{ return _TIME_PUBLISH; }
			set
			{
				this.OnPropertyValueChange(_.TIME_PUBLISH,_TIME_PUBLISH,value);
				this._TIME_PUBLISH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TIME_UNPUBLISH
		{
			get{ return _TIME_UNPUBLISH; }
			set
			{
				this.OnPropertyValueChange(_.TIME_UNPUBLISH,_TIME_UNPUBLISH,value);
				this._TIME_UNPUBLISH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string SUMMARY
		{
			get{ return _SUMMARY; }
			set
			{
				this.OnPropertyValueChange(_.SUMMARY,_SUMMARY,value);
				this._SUMMARY=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? PROP_TOP
		{
			get{ return _PROP_TOP; }
			set
			{
				this.OnPropertyValueChange(_.PROP_TOP,_PROP_TOP,value);
				this._PROP_TOP=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? PROP_PIC
		{
			get{ return _PROP_PIC; }
			set
			{
				this.OnPropertyValueChange(_.PROP_PIC,_PROP_PIC,value);
				this._PROP_PIC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HTML_PATH
		{
			get{ return _HTML_PATH; }
			set
			{
				this.OnPropertyValueChange(_.HTML_PATH,_HTML_PATH,value);
				this._HTML_PATH=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string URL_LINK
		{
			get{ return _URL_LINK; }
			set
			{
				this.OnPropertyValueChange(_.URL_LINK,_URL_LINK,value);
				this._URL_LINK=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string RELATION_ID
		{
			get{ return _RELATION_ID; }
			set
			{
				this.OnPropertyValueChange(_.RELATION_ID,_RELATION_ID,value);
				this._RELATION_ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string HOT_ID
		{
			get{ return _HOT_ID; }
			set
			{
				this.OnPropertyValueChange(_.HOT_ID,_HOT_ID,value);
				this._HOT_ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string TITLE_COLOR
		{
			get{ return _TITLE_COLOR; }
			set
			{
				this.OnPropertyValueChange(_.TITLE_COLOR,_TITLE_COLOR,value);
				this._TITLE_COLOR=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? STATE
		{
			get{ return _STATE; }
			set
			{
				this.OnPropertyValueChange(_.STATE,_STATE,value);
				this._STATE=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? Click
		{
			get{ return _Click; }
			set
			{
				this.OnPropertyValueChange(_.Click,_Click,value);
				this._Click=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string PIC
		{
			get{ return _PIC; }
			set
			{
				this.OnPropertyValueChange(_.PIC,_PIC,value);
				this._PIC=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string INFO_ID
		{
			get{ return _INFO_ID; }
			set
			{
				this.OnPropertyValueChange(_.INFO_ID,_INFO_ID,value);
				this._INFO_ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public DateTime? TIME_LAST
		{
			get{ return _TIME_LAST; }
			set
			{
				this.OnPropertyValueChange(_.TIME_LAST,_TIME_LAST,value);
				this._TIME_LAST=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? USER_ID
		{
			get{ return _USER_ID; }
			set
			{
				this.OnPropertyValueChange(_.USER_ID,_USER_ID,value);
				this._USER_ID=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string USER_NAME
		{
			get{ return _USER_NAME; }
			set
			{
				this.OnPropertyValueChange(_.USER_NAME,_USER_NAME,value);
				this._USER_NAME=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public decimal? USER_ID_PUB
		{
			get{ return _USER_ID_PUB; }
			set
			{
				this.OnPropertyValueChange(_.USER_ID_PUB,_USER_ID_PUB,value);
				this._USER_ID_PUB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string USER_NAME_PUB
		{
			get{ return _USER_NAME_PUB; }
			set
			{
				this.OnPropertyValueChange(_.USER_NAME_PUB,_USER_NAME_PUB,value);
				this._USER_NAME_PUB=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string MP3
		{
			get{ return _MP3; }
			set
			{
				this.OnPropertyValueChange(_.MP3,_MP3,value);
				this._MP3=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? IPTV
		{
			get{ return _IPTV; }
			set
			{
				this.OnPropertyValueChange(_.IPTV,_IPTV,value);
				this._IPTV=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FLV
		{
			get{ return _FLV; }
			set
			{
				this.OnPropertyValueChange(_.FLV,_FLV,value);
				this._FLV=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public bool? PROP_INDEX
		{
			get{ return _PROP_INDEX; }
			set
			{
				this.OnPropertyValueChange(_.PROP_INDEX,_PROP_INDEX,value);
				this._PROP_INDEX=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string City
		{
			get{ return _City; }
			set
			{
				this.OnPropertyValueChange(_.City,_City,value);
				this._City=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string CustomType
		{
			get{ return _CustomType; }
			set
			{
				this.OnPropertyValueChange(_.CustomType,_CustomType,value);
				this._CustomType=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FileUser
		{
			get{ return _FileUser; }
			set
			{
				this.OnPropertyValueChange(_.FileUser,_FileUser,value);
				this._FileUser=value;
			}
		}
		/// <summary>
		/// 
		/// </summary>
		public string FileCode
		{
			get{ return _FileCode; }
			set
			{
				this.OnPropertyValueChange(_.FileCode,_FileCode,value);
				this._FileCode=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.ID};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.ID,
				_.TITLE,
				_.LONGTITLE,
				_.INFOTYPE,
				_.ORDERID,
				_.INFOSOURCE,
				_.KEYWORD,
				_.TIME_PUBLISH,
				_.TIME_UNPUBLISH,
				_.SUMMARY,
				_.PROP_TOP,
				_.PROP_PIC,
				_.HTML_PATH,
				_.URL_LINK,
				_.RELATION_ID,
				_.HOT_ID,
				_.TITLE_COLOR,
				_.STATE,
				_.Click,
				_.PIC,
				_.INFO_ID,
				_.TIME_LAST,
				_.USER_ID,
				_.USER_NAME,
				_.USER_ID_PUB,
				_.USER_NAME_PUB,
				_.MP3,
				_.IPTV,
				_.FLV,
				_.PROP_INDEX,
				_.City,
				_.CustomType,
				_.FileUser,
				_.FileCode};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._ID,
				this._TITLE,
				this._LONGTITLE,
				this._INFOTYPE,
				this._ORDERID,
				this._INFOSOURCE,
				this._KEYWORD,
				this._TIME_PUBLISH,
				this._TIME_UNPUBLISH,
				this._SUMMARY,
				this._PROP_TOP,
				this._PROP_PIC,
				this._HTML_PATH,
				this._URL_LINK,
				this._RELATION_ID,
				this._HOT_ID,
				this._TITLE_COLOR,
				this._STATE,
				this._Click,
				this._PIC,
				this._INFO_ID,
				this._TIME_LAST,
				this._USER_ID,
				this._USER_NAME,
				this._USER_ID_PUB,
				this._USER_NAME_PUB,
				this._MP3,
				this._IPTV,
				this._FLV,
				this._PROP_INDEX,
				this._City,
				this._CustomType,
				this._FileUser,
				this._FileCode};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._ID = DataUtils.ConvertValue<decimal>(reader["ID"]);
			this._TITLE = DataUtils.ConvertValue<string>(reader["TITLE"]);
			this._LONGTITLE = DataUtils.ConvertValue<string>(reader["LONGTITLE"]);
			this._INFOTYPE = DataUtils.ConvertValue<decimal?>(reader["INFOTYPE"]);
			this._ORDERID = DataUtils.ConvertValue<decimal?>(reader["ORDERID"]);
			this._INFOSOURCE = DataUtils.ConvertValue<string>(reader["INFOSOURCE"]);
			this._KEYWORD = DataUtils.ConvertValue<string>(reader["KEYWORD"]);
			this._TIME_PUBLISH = DataUtils.ConvertValue<DateTime?>(reader["TIME_PUBLISH"]);
			this._TIME_UNPUBLISH = DataUtils.ConvertValue<DateTime?>(reader["TIME_UNPUBLISH"]);
			this._SUMMARY = DataUtils.ConvertValue<string>(reader["SUMMARY"]);
			this._PROP_TOP = DataUtils.ConvertValue<bool?>(reader["PROP_TOP"]);
			this._PROP_PIC = DataUtils.ConvertValue<bool?>(reader["PROP_PIC"]);
			this._HTML_PATH = DataUtils.ConvertValue<string>(reader["HTML_PATH"]);
			this._URL_LINK = DataUtils.ConvertValue<string>(reader["URL_LINK"]);
			this._RELATION_ID = DataUtils.ConvertValue<string>(reader["RELATION_ID"]);
			this._HOT_ID = DataUtils.ConvertValue<string>(reader["HOT_ID"]);
			this._TITLE_COLOR = DataUtils.ConvertValue<string>(reader["TITLE_COLOR"]);
			this._STATE = DataUtils.ConvertValue<decimal?>(reader["STATE"]);
			this._Click = DataUtils.ConvertValue<decimal?>(reader["Click"]);
			this._PIC = DataUtils.ConvertValue<string>(reader["PIC"]);
			this._INFO_ID = DataUtils.ConvertValue<string>(reader["INFO_ID"]);
			this._TIME_LAST = DataUtils.ConvertValue<DateTime?>(reader["TIME_LAST"]);
			this._USER_ID = DataUtils.ConvertValue<decimal?>(reader["USER_ID"]);
			this._USER_NAME = DataUtils.ConvertValue<string>(reader["USER_NAME"]);
			this._USER_ID_PUB = DataUtils.ConvertValue<decimal?>(reader["USER_ID_PUB"]);
			this._USER_NAME_PUB = DataUtils.ConvertValue<string>(reader["USER_NAME_PUB"]);
			this._MP3 = DataUtils.ConvertValue<string>(reader["MP3"]);
			this._IPTV = DataUtils.ConvertValue<bool?>(reader["IPTV"]);
			this._FLV = DataUtils.ConvertValue<string>(reader["FLV"]);
			this._PROP_INDEX = DataUtils.ConvertValue<bool?>(reader["PROP_INDEX"]);
			this._City = DataUtils.ConvertValue<string>(reader["City"]);
			this._CustomType = DataUtils.ConvertValue<string>(reader["CustomType"]);
			this._FileUser = DataUtils.ConvertValue<string>(reader["FileUser"]);
			this._FileCode = DataUtils.ConvertValue<string>(reader["FileCode"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._ID = DataUtils.ConvertValue<decimal>(row["ID"]);
			this._TITLE = DataUtils.ConvertValue<string>(row["TITLE"]);
			this._LONGTITLE = DataUtils.ConvertValue<string>(row["LONGTITLE"]);
			this._INFOTYPE = DataUtils.ConvertValue<decimal?>(row["INFOTYPE"]);
			this._ORDERID = DataUtils.ConvertValue<decimal?>(row["ORDERID"]);
			this._INFOSOURCE = DataUtils.ConvertValue<string>(row["INFOSOURCE"]);
			this._KEYWORD = DataUtils.ConvertValue<string>(row["KEYWORD"]);
			this._TIME_PUBLISH = DataUtils.ConvertValue<DateTime?>(row["TIME_PUBLISH"]);
			this._TIME_UNPUBLISH = DataUtils.ConvertValue<DateTime?>(row["TIME_UNPUBLISH"]);
			this._SUMMARY = DataUtils.ConvertValue<string>(row["SUMMARY"]);
			this._PROP_TOP = DataUtils.ConvertValue<bool?>(row["PROP_TOP"]);
			this._PROP_PIC = DataUtils.ConvertValue<bool?>(row["PROP_PIC"]);
			this._HTML_PATH = DataUtils.ConvertValue<string>(row["HTML_PATH"]);
			this._URL_LINK = DataUtils.ConvertValue<string>(row["URL_LINK"]);
			this._RELATION_ID = DataUtils.ConvertValue<string>(row["RELATION_ID"]);
			this._HOT_ID = DataUtils.ConvertValue<string>(row["HOT_ID"]);
			this._TITLE_COLOR = DataUtils.ConvertValue<string>(row["TITLE_COLOR"]);
			this._STATE = DataUtils.ConvertValue<decimal?>(row["STATE"]);
			this._Click = DataUtils.ConvertValue<decimal?>(row["Click"]);
			this._PIC = DataUtils.ConvertValue<string>(row["PIC"]);
			this._INFO_ID = DataUtils.ConvertValue<string>(row["INFO_ID"]);
			this._TIME_LAST = DataUtils.ConvertValue<DateTime?>(row["TIME_LAST"]);
			this._USER_ID = DataUtils.ConvertValue<decimal?>(row["USER_ID"]);
			this._USER_NAME = DataUtils.ConvertValue<string>(row["USER_NAME"]);
			this._USER_ID_PUB = DataUtils.ConvertValue<decimal?>(row["USER_ID_PUB"]);
			this._USER_NAME_PUB = DataUtils.ConvertValue<string>(row["USER_NAME_PUB"]);
			this._MP3 = DataUtils.ConvertValue<string>(row["MP3"]);
			this._IPTV = DataUtils.ConvertValue<bool?>(row["IPTV"]);
			this._FLV = DataUtils.ConvertValue<string>(row["FLV"]);
			this._PROP_INDEX = DataUtils.ConvertValue<bool?>(row["PROP_INDEX"]);
			this._City = DataUtils.ConvertValue<string>(row["City"]);
			this._CustomType = DataUtils.ConvertValue<string>(row["CustomType"]);
			this._FileUser = DataUtils.ConvertValue<string>(row["FileUser"]);
			this._FileCode = DataUtils.ConvertValue<string>(row["FileCode"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","CONTENT_LIST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ID = new Field("ID","CONTENT_LIST","ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TITLE = new Field("TITLE","CONTENT_LIST","TITLE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field LONGTITLE = new Field("LONGTITLE","CONTENT_LIST","LONGTITLE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field INFOTYPE = new Field("INFOTYPE","CONTENT_LIST","INFOTYPE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field ORDERID = new Field("ORDERID","CONTENT_LIST","ORDERID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field INFOSOURCE = new Field("INFOSOURCE","CONTENT_LIST","INFOSOURCE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field KEYWORD = new Field("KEYWORD","CONTENT_LIST","KEYWORD");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TIME_PUBLISH = new Field("TIME_PUBLISH","CONTENT_LIST","TIME_PUBLISH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TIME_UNPUBLISH = new Field("TIME_UNPUBLISH","CONTENT_LIST","TIME_UNPUBLISH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field SUMMARY = new Field("SUMMARY","CONTENT_LIST","SUMMARY");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROP_TOP = new Field("PROP_TOP","CONTENT_LIST","PROP_TOP");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROP_PIC = new Field("PROP_PIC","CONTENT_LIST","PROP_PIC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HTML_PATH = new Field("HTML_PATH","CONTENT_LIST","HTML_PATH");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field URL_LINK = new Field("URL_LINK","CONTENT_LIST","URL_LINK");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field RELATION_ID = new Field("RELATION_ID","CONTENT_LIST","RELATION_ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field HOT_ID = new Field("HOT_ID","CONTENT_LIST","HOT_ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TITLE_COLOR = new Field("TITLE_COLOR","CONTENT_LIST","TITLE_COLOR");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field STATE = new Field("STATE","CONTENT_LIST","STATE");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field Click = new Field("Click","CONTENT_LIST","Click");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PIC = new Field("PIC","CONTENT_LIST","PIC");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field INFO_ID = new Field("INFO_ID","CONTENT_LIST","INFO_ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field TIME_LAST = new Field("TIME_LAST","CONTENT_LIST","TIME_LAST");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field USER_ID = new Field("USER_ID","CONTENT_LIST","USER_ID");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field USER_NAME = new Field("USER_NAME","CONTENT_LIST","USER_NAME");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field USER_ID_PUB = new Field("USER_ID_PUB","CONTENT_LIST","USER_ID_PUB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field USER_NAME_PUB = new Field("USER_NAME_PUB","CONTENT_LIST","USER_NAME_PUB");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field MP3 = new Field("MP3","CONTENT_LIST","MP3");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field IPTV = new Field("IPTV","CONTENT_LIST","IPTV");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FLV = new Field("FLV","CONTENT_LIST","FLV");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field PROP_INDEX = new Field("PROP_INDEX","CONTENT_LIST","PROP_INDEX");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field City = new Field("City","CONTENT_LIST","City");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field CustomType = new Field("CustomType","CONTENT_LIST","CustomType");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FileUser = new Field("FileUser","CONTENT_LIST","FileUser");
			/// <summary>
			/// 
			/// </summary>
			public readonly static Field FileCode = new Field("FileCode","CONTENT_LIST","FileCode");
		}
		#endregion


	}
}

