//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类DeviceDataInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class DeviceDataInfo : Entity 
	{
		public DeviceDataInfo():base("DeviceDataInfo") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _DeviceSerialnum;
		private string _ShowValue;
		private int _OriginalData;
		private decimal _ProcessedValue;
		private bool _IsException;
		private decimal _Max;
		private decimal _Min;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 设施编码
		/// </summary>
		public string DeviceSerialnum
		{
			get{ return _DeviceSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.DeviceSerialnum,_DeviceSerialnum,value);
				this._DeviceSerialnum=value;
			}
		}
		/// <summary>
		/// 显示值
		/// </summary>
		public string ShowValue
		{
			get{ return _ShowValue; }
			set
			{
				this.OnPropertyValueChange(_.ShowValue,_ShowValue,value);
				this._ShowValue=value;
			}
		}
		/// <summary>
		/// 未处理值
		/// </summary>
		public int OriginalData
		{
			get{ return _OriginalData; }
			set
			{
				this.OnPropertyValueChange(_.OriginalData,_OriginalData,value);
				this._OriginalData=value;
			}
		}
		/// <summary>
		/// 处理值
		/// </summary>
		public decimal ProcessedValue
		{
			get{ return _ProcessedValue; }
			set
			{
				this.OnPropertyValueChange(_.ProcessedValue,_ProcessedValue,value);
				this._ProcessedValue=value;
			}
		}
		/// <summary>
		/// 是否异常
		/// </summary>
		public bool IsException
		{
			get{ return _IsException; }
			set
			{
				this.OnPropertyValueChange(_.IsException,_IsException,value);
				this._IsException=value;
			}
		}
		/// <summary>
		/// 上限
		/// </summary>
		public decimal Max
		{
			get{ return _Max; }
			set
			{
				this.OnPropertyValueChange(_.Max,_Max,value);
				this._Max=value;
			}
		}
		/// <summary>
		/// 下限
		/// </summary>
		public decimal Min
		{
			get{ return _Min; }
			set
			{
				this.OnPropertyValueChange(_.Min,_Min,value);
				this._Min=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.DeviceSerialnum,
				_.ShowValue,
				_.OriginalData,
				_.ProcessedValue,
				_.IsException,
				_.Max,
				_.Min,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._DeviceSerialnum,
				this._ShowValue,
				this._OriginalData,
				this._ProcessedValue,
				this._IsException,
				this._Max,
				this._Min,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._DeviceSerialnum = DataUtils.ConvertValue<string>(reader["DeviceSerialnum"]);
			this._ShowValue = DataUtils.ConvertValue<string>(reader["ShowValue"]);
			this._OriginalData = DataUtils.ConvertValue<int>(reader["OriginalData"]);
			this._ProcessedValue = DataUtils.ConvertValue<decimal>(reader["ProcessedValue"]);
			this._IsException = DataUtils.ConvertValue<bool>(reader["IsException"]);
			this._Max = DataUtils.ConvertValue<decimal>(reader["Max"]);
			this._Min = DataUtils.ConvertValue<decimal>(reader["Min"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._DeviceSerialnum = DataUtils.ConvertValue<string>(row["DeviceSerialnum"]);
			this._ShowValue = DataUtils.ConvertValue<string>(row["ShowValue"]);
			this._OriginalData = DataUtils.ConvertValue<int>(row["OriginalData"]);
			this._ProcessedValue = DataUtils.ConvertValue<decimal>(row["ProcessedValue"]);
			this._IsException = DataUtils.ConvertValue<bool>(row["IsException"]);
			this._Max = DataUtils.ConvertValue<decimal>(row["Max"]);
			this._Min = DataUtils.ConvertValue<decimal>(row["Min"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","DeviceDataInfo");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","DeviceDataInfo","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","DeviceDataInfo","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","DeviceDataInfo","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","DeviceDataInfo","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","DeviceDataInfo","更新用户");
			/// <summary>
			/// 设施编码
			/// </summary>
			public readonly static Field DeviceSerialnum = new Field("DeviceSerialnum","DeviceDataInfo","设施编码");
			/// <summary>
			/// 显示值
			/// </summary>
			public readonly static Field ShowValue = new Field("ShowValue","DeviceDataInfo","显示值");
			/// <summary>
			/// 未处理值
			/// </summary>
			public readonly static Field OriginalData = new Field("OriginalData","DeviceDataInfo","未处理值");
			/// <summary>
			/// 处理值
			/// </summary>
			public readonly static Field ProcessedValue = new Field("ProcessedValue","DeviceDataInfo","处理值");
			/// <summary>
			/// 是否异常
			/// </summary>
			public readonly static Field IsException = new Field("IsException","DeviceDataInfo","是否异常");
			/// <summary>
			/// 上限
			/// </summary>
			public readonly static Field Max = new Field("Max","DeviceDataInfo","上限");
			/// <summary>
			/// 下限
			/// </summary>
			public readonly static Field Min = new Field("Min","DeviceDataInfo","下限");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","DeviceDataInfo","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","DeviceDataInfo","备注");
		}
		#endregion


	}
}

