//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类Facility 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class Facility : Entity 
	{
		public Facility():base("Facility") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _Name;
		private string _FarmSerialnum;
		private string _FacilityTypeSerialnum;
		private string _Address;
		private string _PhotoUrl;
		private string _ContactMan;
		private string _ContactPhone;
		private string _ContactMobile;
		private int _Status;
		private string _Introduce;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 基地编码
		/// </summary>
		public string FarmSerialnum
		{
			get{ return _FarmSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.FarmSerialnum,_FarmSerialnum,value);
				this._FarmSerialnum=value;
			}
		}
		/// <summary>
		/// 设施类型
		/// </summary>
		public string FacilityTypeSerialnum
		{
			get{ return _FacilityTypeSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.FacilityTypeSerialnum,_FacilityTypeSerialnum,value);
				this._FacilityTypeSerialnum=value;
			}
		}
		/// <summary>
		/// 地址
		/// </summary>
		public string Address
		{
			get{ return _Address; }
			set
			{
				this.OnPropertyValueChange(_.Address,_Address,value);
				this._Address=value;
			}
		}
		/// <summary>
		/// 形象图片
		/// </summary>
		public string PhotoUrl
		{
			get{ return _PhotoUrl; }
			set
			{
				this.OnPropertyValueChange(_.PhotoUrl,_PhotoUrl,value);
				this._PhotoUrl=value;
			}
		}
		/// <summary>
		/// 联系人
		/// </summary>
		public string ContactMan
		{
			get{ return _ContactMan; }
			set
			{
				this.OnPropertyValueChange(_.ContactMan,_ContactMan,value);
				this._ContactMan=value;
			}
		}
		/// <summary>
		/// 联系电话
		/// </summary>
		public string ContactPhone
		{
			get{ return _ContactPhone; }
			set
			{
				this.OnPropertyValueChange(_.ContactPhone,_ContactPhone,value);
				this._ContactPhone=value;
			}
		}
		/// <summary>
		/// 手机
		/// </summary>
		public string ContactMobile
		{
			get{ return _ContactMobile; }
			set
			{
				this.OnPropertyValueChange(_.ContactMobile,_ContactMobile,value);
				this._ContactMobile=value;
			}
		}
		/// <summary>
		/// 状态
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 设施介绍
		/// </summary>
		public string Introduce
		{
			get{ return _Introduce; }
			set
			{
				this.OnPropertyValueChange(_.Introduce,_Introduce,value);
				this._Introduce=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.Name,
				_.FarmSerialnum,
				_.FacilityTypeSerialnum,
				_.Address,
				_.PhotoUrl,
				_.ContactMan,
				_.ContactPhone,
				_.ContactMobile,
				_.Status,
				_.Introduce,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._Name,
				this._FarmSerialnum,
				this._FacilityTypeSerialnum,
				this._Address,
				this._PhotoUrl,
				this._ContactMan,
				this._ContactPhone,
				this._ContactMobile,
				this._Status,
				this._Introduce,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._FarmSerialnum = DataUtils.ConvertValue<string>(reader["FarmSerialnum"]);
			this._FacilityTypeSerialnum = DataUtils.ConvertValue<string>(reader["FacilityTypeSerialnum"]);
			this._Address = DataUtils.ConvertValue<string>(reader["Address"]);
			this._PhotoUrl = DataUtils.ConvertValue<string>(reader["PhotoUrl"]);
			this._ContactMan = DataUtils.ConvertValue<string>(reader["ContactMan"]);
			this._ContactPhone = DataUtils.ConvertValue<string>(reader["ContactPhone"]);
			this._ContactMobile = DataUtils.ConvertValue<string>(reader["ContactMobile"]);
			this._Status = DataUtils.ConvertValue<int>(reader["Status"]);
			this._Introduce = DataUtils.ConvertValue<string>(reader["Introduce"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._FarmSerialnum = DataUtils.ConvertValue<string>(row["FarmSerialnum"]);
			this._FacilityTypeSerialnum = DataUtils.ConvertValue<string>(row["FacilityTypeSerialnum"]);
			this._Address = DataUtils.ConvertValue<string>(row["Address"]);
			this._PhotoUrl = DataUtils.ConvertValue<string>(row["PhotoUrl"]);
			this._ContactMan = DataUtils.ConvertValue<string>(row["ContactMan"]);
			this._ContactPhone = DataUtils.ConvertValue<string>(row["ContactPhone"]);
			this._ContactMobile = DataUtils.ConvertValue<string>(row["ContactMobile"]);
			this._Status = DataUtils.ConvertValue<int>(row["Status"]);
			this._Introduce = DataUtils.ConvertValue<string>(row["Introduce"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","Facility");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","Facility","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","Facility","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","Facility","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","Facility","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","Facility","更新用户");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","Facility","名称");
			/// <summary>
			/// 基地编码
			/// </summary>
			public readonly static Field FarmSerialnum = new Field("FarmSerialnum","Facility","基地编码");
			/// <summary>
			/// 设施类型
			/// </summary>
			public readonly static Field FacilityTypeSerialnum = new Field("FacilityTypeSerialnum","Facility","设施类型");
			/// <summary>
			/// 地址
			/// </summary>
			public readonly static Field Address = new Field("Address","Facility","地址");
			/// <summary>
			/// 形象图片
			/// </summary>
			public readonly static Field PhotoUrl = new Field("PhotoUrl","Facility","形象图片");
			/// <summary>
			/// 联系人
			/// </summary>
			public readonly static Field ContactMan = new Field("ContactMan","Facility","联系人");
			/// <summary>
			/// 联系电话
			/// </summary>
			public readonly static Field ContactPhone = new Field("ContactPhone","Facility","联系电话");
			/// <summary>
			/// 手机
			/// </summary>
			public readonly static Field ContactMobile = new Field("ContactMobile","Facility","手机");
			/// <summary>
			/// 状态
			/// </summary>
			public readonly static Field Status = new Field("Status","Facility","状态");
			/// <summary>
			/// 设施介绍
			/// </summary>
			public readonly static Field Introduce = new Field("Introduce","Facility","设施介绍");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","Facility","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","Facility","备注");
		}
		#endregion


	}
}

