//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类FacilityProduceInfo 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class FacilityProduceInfo : Entity 
	{
		public FacilityProduceInfo():base("FacilityProduceInfo") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _Name;
		private string _FacilitySerialnum;
		private string _AgrProductObjectSerialnum;
		private string _Description;
		private bool _Status;
		private DateTime? _StartTime;
		private DateTime? _EndTime;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 名称
		/// </summary>
		public string Name
		{
			get{ return _Name; }
			set
			{
				this.OnPropertyValueChange(_.Name,_Name,value);
				this._Name=value;
			}
		}
		/// <summary>
		/// 设施编码
		/// </summary>
		public string FacilitySerialnum
		{
			get{ return _FacilitySerialnum; }
			set
			{
				this.OnPropertyValueChange(_.FacilitySerialnum,_FacilitySerialnum,value);
				this._FacilitySerialnum=value;
			}
		}
		/// <summary>
		/// 品种
		/// </summary>
		public string AgrProductObjectSerialnum
		{
			get{ return _AgrProductObjectSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.AgrProductObjectSerialnum,_AgrProductObjectSerialnum,value);
				this._AgrProductObjectSerialnum=value;
			}
		}
		/// <summary>
		/// 说明
		/// </summary>
		public string Description
		{
			get{ return _Description; }
			set
			{
				this.OnPropertyValueChange(_.Description,_Description,value);
				this._Description=value;
			}
		}
		/// <summary>
		/// 状态
		/// </summary>
		public bool Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 种植开始时间
		/// </summary>
		public DateTime? StartTime
		{
			get{ return _StartTime; }
			set
			{
				this.OnPropertyValueChange(_.StartTime,_StartTime,value);
				this._StartTime=value;
			}
		}
		/// <summary>
		/// 种植结束时间
		/// </summary>
		public DateTime? EndTime
		{
			get{ return _EndTime; }
			set
			{
				this.OnPropertyValueChange(_.EndTime,_EndTime,value);
				this._EndTime=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.Name,
				_.FacilitySerialnum,
				_.AgrProductObjectSerialnum,
				_.Description,
				_.Status,
				_.StartTime,
				_.EndTime,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._Name,
				this._FacilitySerialnum,
				this._AgrProductObjectSerialnum,
				this._Description,
				this._Status,
				this._StartTime,
				this._EndTime,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._Name = DataUtils.ConvertValue<string>(reader["Name"]);
			this._FacilitySerialnum = DataUtils.ConvertValue<string>(reader["FacilitySerialnum"]);
			this._AgrProductObjectSerialnum = DataUtils.ConvertValue<string>(reader["AgrProductObjectSerialnum"]);
			this._Description = DataUtils.ConvertValue<string>(reader["Description"]);
			this._Status = DataUtils.ConvertValue<bool>(reader["Status"]);
			this._StartTime = DataUtils.ConvertValue<DateTime?>(reader["StartTime"]);
			this._EndTime = DataUtils.ConvertValue<DateTime?>(reader["EndTime"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._Name = DataUtils.ConvertValue<string>(row["Name"]);
			this._FacilitySerialnum = DataUtils.ConvertValue<string>(row["FacilitySerialnum"]);
			this._AgrProductObjectSerialnum = DataUtils.ConvertValue<string>(row["AgrProductObjectSerialnum"]);
			this._Description = DataUtils.ConvertValue<string>(row["Description"]);
			this._Status = DataUtils.ConvertValue<bool>(row["Status"]);
			this._StartTime = DataUtils.ConvertValue<DateTime?>(row["StartTime"]);
			this._EndTime = DataUtils.ConvertValue<DateTime?>(row["EndTime"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","FacilityProduceInfo");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","FacilityProduceInfo","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","FacilityProduceInfo","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","FacilityProduceInfo","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","FacilityProduceInfo","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","FacilityProduceInfo","更新用户");
			/// <summary>
			/// 名称
			/// </summary>
			public readonly static Field Name = new Field("Name","FacilityProduceInfo","名称");
			/// <summary>
			/// 设施编码
			/// </summary>
			public readonly static Field FacilitySerialnum = new Field("FacilitySerialnum","FacilityProduceInfo","设施编码");
			/// <summary>
			/// 品种
			/// </summary>
			public readonly static Field AgrProductObjectSerialnum = new Field("AgrProductObjectSerialnum","FacilityProduceInfo","品种");
			/// <summary>
			/// 说明
			/// </summary>
			public readonly static Field Description = new Field("Description","FacilityProduceInfo","说明");
			/// <summary>
			/// 状态
			/// </summary>
			public readonly static Field Status = new Field("Status","FacilityProduceInfo","状态");
			/// <summary>
			/// 种植开始时间
			/// </summary>
			public readonly static Field StartTime = new Field("StartTime","FacilityProduceInfo","种植开始时间");
			/// <summary>
			/// 种植结束时间
			/// </summary>
			public readonly static Field EndTime = new Field("EndTime","FacilityProduceInfo","种植结束时间");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","FacilityProduceInfo","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","FacilityProduceInfo","备注");
		}
		#endregion


	}
}

