//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类SysUser 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class SysUser : Entity 
	{
		public SysUser():base("SysUser") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _LoginName;
		private string _UserName;
		private string _Email;
		private string _QQ;
		private string _Password;
		private int _Status;
		private string _LastIP;
		private DateTime? _LastTime;
		private string _LastUrl;
		private string _SysRoleSerialnum;
		private string _SysDepartmentSerialnum;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 登录名
		/// </summary>
		public string LoginName
		{
			get{ return _LoginName; }
			set
			{
				this.OnPropertyValueChange(_.LoginName,_LoginName,value);
				this._LoginName=value;
			}
		}
		/// <summary>
		/// 姓名
		/// </summary>
		public string UserName
		{
			get{ return _UserName; }
			set
			{
				this.OnPropertyValueChange(_.UserName,_UserName,value);
				this._UserName=value;
			}
		}
		/// <summary>
		/// 邮箱
		/// </summary>
		public string Email
		{
			get{ return _Email; }
			set
			{
				this.OnPropertyValueChange(_.Email,_Email,value);
				this._Email=value;
			}
		}
		/// <summary>
		/// QQ
		/// </summary>
		public string QQ
		{
			get{ return _QQ; }
			set
			{
				this.OnPropertyValueChange(_.QQ,_QQ,value);
				this._QQ=value;
			}
		}
		/// <summary>
		/// 密码
		/// </summary>
		public string Password
		{
			get{ return _Password; }
			set
			{
				this.OnPropertyValueChange(_.Password,_Password,value);
				this._Password=value;
			}
		}
		/// <summary>
		/// 状态。状态（1：启用，0：禁用，2...）
		/// </summary>
		public int Status
		{
			get{ return _Status; }
			set
			{
				this.OnPropertyValueChange(_.Status,_Status,value);
				this._Status=value;
			}
		}
		/// <summary>
		/// 最后登录IP
		/// </summary>
		public string LastIP
		{
			get{ return _LastIP; }
			set
			{
				this.OnPropertyValueChange(_.LastIP,_LastIP,value);
				this._LastIP=value;
			}
		}
		/// <summary>
		/// 最后登录时间
		/// </summary>
		public DateTime? LastTime
		{
			get{ return _LastTime; }
			set
			{
				this.OnPropertyValueChange(_.LastTime,_LastTime,value);
				this._LastTime=value;
			}
		}
		/// <summary>
		/// 上次URL
		/// </summary>
		public string LastUrl
		{
			get{ return _LastUrl; }
			set
			{
				this.OnPropertyValueChange(_.LastUrl,_LastUrl,value);
				this._LastUrl=value;
			}
		}
		/// <summary>
		/// 角色
		/// </summary>
		public string SysRoleSerialnum
		{
			get{ return _SysRoleSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysRoleSerialnum,_SysRoleSerialnum,value);
				this._SysRoleSerialnum=value;
			}
		}
		/// <summary>
		/// 所属机构
		/// </summary>
		public string SysDepartmentSerialnum
		{
			get{ return _SysDepartmentSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysDepartmentSerialnum,_SysDepartmentSerialnum,value);
				this._SysDepartmentSerialnum=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.LoginName,
				_.UserName,
				_.Email,
				_.QQ,
				_.Password,
				_.Status,
				_.LastIP,
				_.LastTime,
				_.LastUrl,
				_.SysRoleSerialnum,
				_.SysDepartmentSerialnum,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._LoginName,
				this._UserName,
				this._Email,
				this._QQ,
				this._Password,
				this._Status,
				this._LastIP,
				this._LastTime,
				this._LastUrl,
				this._SysRoleSerialnum,
				this._SysDepartmentSerialnum,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._LoginName = DataUtils.ConvertValue<string>(reader["LoginName"]);
			this._UserName = DataUtils.ConvertValue<string>(reader["UserName"]);
			this._Email = DataUtils.ConvertValue<string>(reader["Email"]);
			this._QQ = DataUtils.ConvertValue<string>(reader["QQ"]);
			this._Password = DataUtils.ConvertValue<string>(reader["Password"]);
			this._Status = DataUtils.ConvertValue<int>(reader["Status"]);
			this._LastIP = DataUtils.ConvertValue<string>(reader["LastIP"]);
			this._LastTime = DataUtils.ConvertValue<DateTime?>(reader["LastTime"]);
			this._LastUrl = DataUtils.ConvertValue<string>(reader["LastUrl"]);
			this._SysRoleSerialnum = DataUtils.ConvertValue<string>(reader["SysRoleSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(reader["SysDepartmentSerialnum"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._LoginName = DataUtils.ConvertValue<string>(row["LoginName"]);
			this._UserName = DataUtils.ConvertValue<string>(row["UserName"]);
			this._Email = DataUtils.ConvertValue<string>(row["Email"]);
			this._QQ = DataUtils.ConvertValue<string>(row["QQ"]);
			this._Password = DataUtils.ConvertValue<string>(row["Password"]);
			this._Status = DataUtils.ConvertValue<int>(row["Status"]);
			this._LastIP = DataUtils.ConvertValue<string>(row["LastIP"]);
			this._LastTime = DataUtils.ConvertValue<DateTime?>(row["LastTime"]);
			this._LastUrl = DataUtils.ConvertValue<string>(row["LastUrl"]);
			this._SysRoleSerialnum = DataUtils.ConvertValue<string>(row["SysRoleSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(row["SysDepartmentSerialnum"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","SysUser");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","SysUser","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","SysUser","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","SysUser","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","SysUser","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","SysUser","更新用户");
			/// <summary>
			/// 登录名
			/// </summary>
			public readonly static Field LoginName = new Field("LoginName","SysUser","登录名");
			/// <summary>
			/// 姓名
			/// </summary>
			public readonly static Field UserName = new Field("UserName","SysUser","姓名");
			/// <summary>
			/// 邮箱
			/// </summary>
			public readonly static Field Email = new Field("Email","SysUser","邮箱");
			/// <summary>
			/// QQ
			/// </summary>
			public readonly static Field QQ = new Field("QQ","SysUser","QQ");
			/// <summary>
			/// 密码
			/// </summary>
			public readonly static Field Password = new Field("Password","SysUser","密码");
			/// <summary>
			/// 状态。状态（1：启用，0：禁用，2...）
			/// </summary>
			public readonly static Field Status = new Field("Status","SysUser","状态。状态（1：启用，0：禁用，2...）");
			/// <summary>
			/// 最后登录IP
			/// </summary>
			public readonly static Field LastIP = new Field("LastIP","SysUser","最后登录IP");
			/// <summary>
			/// 最后登录时间
			/// </summary>
			public readonly static Field LastTime = new Field("LastTime","SysUser","最后登录时间");
			/// <summary>
			/// 上次URL
			/// </summary>
			public readonly static Field LastUrl = new Field("LastUrl","SysUser","上次URL");
			/// <summary>
			/// 角色
			/// </summary>
			public readonly static Field SysRoleSerialnum = new Field("SysRoleSerialnum","SysUser","角色");
			/// <summary>
			/// 所属机构
			/// </summary>
			public readonly static Field SysDepartmentSerialnum = new Field("SysDepartmentSerialnum","SysUser","所属机构");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","SysUser","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","SysUser","备注");
		}
		#endregion


	}
}

