//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类WeatherWarn 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class WeatherWarn : Entity 
	{
		public WeatherWarn():base("WeatherWarn") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _SysDepartmentSerialnum;
		private string _Title;
		private string _Cover;
		private string _Content;
		private int _Views;
		private string _SourceName;
		private string _SourceUrl;
		private DateTime _PublishTime;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 机构编码
		/// </summary>
		public string SysDepartmentSerialnum
		{
			get{ return _SysDepartmentSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysDepartmentSerialnum,_SysDepartmentSerialnum,value);
				this._SysDepartmentSerialnum=value;
			}
		}
		/// <summary>
		/// 标题
		/// </summary>
		public string Title
		{
			get{ return _Title; }
			set
			{
				this.OnPropertyValueChange(_.Title,_Title,value);
				this._Title=value;
			}
		}
		/// <summary>
		/// 封面
		/// </summary>
		public string Cover
		{
			get{ return _Cover; }
			set
			{
				this.OnPropertyValueChange(_.Cover,_Cover,value);
				this._Cover=value;
			}
		}
		/// <summary>
		/// 内容
		/// </summary>
		public string Content
		{
			get{ return _Content; }
			set
			{
				this.OnPropertyValueChange(_.Content,_Content,value);
				this._Content=value;
			}
		}
		/// <summary>
		/// 访问量
		/// </summary>
		public int Views
		{
			get{ return _Views; }
			set
			{
				this.OnPropertyValueChange(_.Views,_Views,value);
				this._Views=value;
			}
		}
		/// <summary>
		/// 来源名称
		/// </summary>
		public string SourceName
		{
			get{ return _SourceName; }
			set
			{
				this.OnPropertyValueChange(_.SourceName,_SourceName,value);
				this._SourceName=value;
			}
		}
		/// <summary>
		/// 来源地址
		/// </summary>
		public string SourceUrl
		{
			get{ return _SourceUrl; }
			set
			{
				this.OnPropertyValueChange(_.SourceUrl,_SourceUrl,value);
				this._SourceUrl=value;
			}
		}
		/// <summary>
		/// 发布时间
		/// </summary>
		public DateTime PublishTime
		{
			get{ return _PublishTime; }
			set
			{
				this.OnPropertyValueChange(_.PublishTime,_PublishTime,value);
				this._PublishTime=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.SysDepartmentSerialnum,
				_.Title,
				_.Cover,
				_.Content,
				_.Views,
				_.SourceName,
				_.SourceUrl,
				_.PublishTime,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._SysDepartmentSerialnum,
				this._Title,
				this._Cover,
				this._Content,
				this._Views,
				this._SourceName,
				this._SourceUrl,
				this._PublishTime,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(reader["SysDepartmentSerialnum"]);
			this._Title = DataUtils.ConvertValue<string>(reader["Title"]);
			this._Cover = DataUtils.ConvertValue<string>(reader["Cover"]);
			this._Content = DataUtils.ConvertValue<string>(reader["Content"]);
			this._Views = DataUtils.ConvertValue<int>(reader["Views"]);
			this._SourceName = DataUtils.ConvertValue<string>(reader["SourceName"]);
			this._SourceUrl = DataUtils.ConvertValue<string>(reader["SourceUrl"]);
			this._PublishTime = DataUtils.ConvertValue<DateTime>(reader["PublishTime"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(row["SysDepartmentSerialnum"]);
			this._Title = DataUtils.ConvertValue<string>(row["Title"]);
			this._Cover = DataUtils.ConvertValue<string>(row["Cover"]);
			this._Content = DataUtils.ConvertValue<string>(row["Content"]);
			this._Views = DataUtils.ConvertValue<int>(row["Views"]);
			this._SourceName = DataUtils.ConvertValue<string>(row["SourceName"]);
			this._SourceUrl = DataUtils.ConvertValue<string>(row["SourceUrl"]);
			this._PublishTime = DataUtils.ConvertValue<DateTime>(row["PublishTime"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","WeatherWarn");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","WeatherWarn","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","WeatherWarn","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","WeatherWarn","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","WeatherWarn","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","WeatherWarn","更新用户");
			/// <summary>
			/// 机构编码
			/// </summary>
			public readonly static Field SysDepartmentSerialnum = new Field("SysDepartmentSerialnum","WeatherWarn","机构编码");
			/// <summary>
			/// 标题
			/// </summary>
			public readonly static Field Title = new Field("Title","WeatherWarn","标题");
			/// <summary>
			/// 封面
			/// </summary>
			public readonly static Field Cover = new Field("Cover","WeatherWarn","封面");
			/// <summary>
			/// 内容
			/// </summary>
			public readonly static Field Content = new Field("Content","WeatherWarn","内容");
			/// <summary>
			/// 访问量
			/// </summary>
			public readonly static Field Views = new Field("Views","WeatherWarn","访问量");
			/// <summary>
			/// 来源名称
			/// </summary>
			public readonly static Field SourceName = new Field("SourceName","WeatherWarn","来源名称");
			/// <summary>
			/// 来源地址
			/// </summary>
			public readonly static Field SourceUrl = new Field("SourceUrl","WeatherWarn","来源地址");
			/// <summary>
			/// 发布时间
			/// </summary>
			public readonly static Field PublishTime = new Field("PublishTime","WeatherWarn","发布时间");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","WeatherWarn","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","WeatherWarn","备注");
		}
		#endregion


	}
}

