//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.8670
//     Support: http://www.cnblogs.com/huxj
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data;
using System.Data.Common;
using Dos.ORM;


namespace AhnqIot.Hxj.DbModel
{

	/// <summary>
	/// 实体类WeatherStation 。(属性说明自动提取数据库字段的描述信息)
	/// </summary>
	[Serializable]
	public class WeatherStation : Entity 
	{
		public WeatherStation():base("WeatherStation") {}

		#region Model
		private string _Serialnum;
		private DateTime _CreateTime;
		private string _CreateSysUserSerialnum;
		private DateTime _UpdateTime;
		private string _UpdateSysUserSerialnum;
		private string _SysDepartmentSerialnum;
		private string _Location;
		private string _Lotitude;
		private string _Latitude;
		private DateTime? _SetupTime;
		private int? _UploadExperiod;
		private string _Introduce;
		private int _Sort;
		private string _Remark;
		/// <summary>
		/// 编码
		/// </summary>
		public string Serialnum
		{
			get{ return _Serialnum; }
			set
			{
				this.OnPropertyValueChange(_.Serialnum,_Serialnum,value);
				this._Serialnum=value;
			}
		}
		/// <summary>
		/// 创建时间
		/// </summary>
		public DateTime CreateTime
		{
			get{ return _CreateTime; }
			set
			{
				this.OnPropertyValueChange(_.CreateTime,_CreateTime,value);
				this._CreateTime=value;
			}
		}
		/// <summary>
		/// 创建用户
		/// </summary>
		public string CreateSysUserSerialnum
		{
			get{ return _CreateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.CreateSysUserSerialnum,_CreateSysUserSerialnum,value);
				this._CreateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 更新时间
		/// </summary>
		public DateTime UpdateTime
		{
			get{ return _UpdateTime; }
			set
			{
				this.OnPropertyValueChange(_.UpdateTime,_UpdateTime,value);
				this._UpdateTime=value;
			}
		}
		/// <summary>
		/// 更新用户
		/// </summary>
		public string UpdateSysUserSerialnum
		{
			get{ return _UpdateSysUserSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.UpdateSysUserSerialnum,_UpdateSysUserSerialnum,value);
				this._UpdateSysUserSerialnum=value;
			}
		}
		/// <summary>
		/// 机构编码
		/// </summary>
		public string SysDepartmentSerialnum
		{
			get{ return _SysDepartmentSerialnum; }
			set
			{
				this.OnPropertyValueChange(_.SysDepartmentSerialnum,_SysDepartmentSerialnum,value);
				this._SysDepartmentSerialnum=value;
			}
		}
		/// <summary>
		/// 安装位置
		/// </summary>
		public string Location
		{
			get{ return _Location; }
			set
			{
				this.OnPropertyValueChange(_.Location,_Location,value);
				this._Location=value;
			}
		}
		/// <summary>
		/// 经度
		/// </summary>
		public string Lotitude
		{
			get{ return _Lotitude; }
			set
			{
				this.OnPropertyValueChange(_.Lotitude,_Lotitude,value);
				this._Lotitude=value;
			}
		}
		/// <summary>
		/// 纬度
		/// </summary>
		public string Latitude
		{
			get{ return _Latitude; }
			set
			{
				this.OnPropertyValueChange(_.Latitude,_Latitude,value);
				this._Latitude=value;
			}
		}
		/// <summary>
		/// 安装时间
		/// </summary>
		public DateTime? SetupTime
		{
			get{ return _SetupTime; }
			set
			{
				this.OnPropertyValueChange(_.SetupTime,_SetupTime,value);
				this._SetupTime=value;
			}
		}
		/// <summary>
		/// 数据上传频率（几分钟上传一次）
		/// </summary>
		public int? UploadExperiod
		{
			get{ return _UploadExperiod; }
			set
			{
				this.OnPropertyValueChange(_.UploadExperiod,_UploadExperiod,value);
				this._UploadExperiod=value;
			}
		}
		/// <summary>
		/// 介绍
		/// </summary>
		public string Introduce
		{
			get{ return _Introduce; }
			set
			{
				this.OnPropertyValueChange(_.Introduce,_Introduce,value);
				this._Introduce=value;
			}
		}
		/// <summary>
		/// 排序
		/// </summary>
		public int Sort
		{
			get{ return _Sort; }
			set
			{
				this.OnPropertyValueChange(_.Sort,_Sort,value);
				this._Sort=value;
			}
		}
		/// <summary>
		/// 备注
		/// </summary>
		public string Remark
		{
			get{ return _Remark; }
			set
			{
				this.OnPropertyValueChange(_.Remark,_Remark,value);
				this._Remark=value;
			}
		}
		#endregion

		#region Method
		/// <summary>
		/// 获取实体中的主键列
		/// </summary>
		public override Field[] GetPrimaryKeyFields()
		{
			return new Field[] {
				_.Serialnum};
		}
		/// <summary>
		/// 获取列信息
		/// </summary>
		public override Field[] GetFields()
		{
			return new Field[] {
				_.Serialnum,
				_.CreateTime,
				_.CreateSysUserSerialnum,
				_.UpdateTime,
				_.UpdateSysUserSerialnum,
				_.SysDepartmentSerialnum,
				_.Location,
				_.Lotitude,
				_.Latitude,
				_.SetupTime,
				_.UploadExperiod,
				_.Introduce,
				_.Sort,
				_.Remark};
		}
		/// <summary>
		/// 获取值信息
		/// </summary>
		public override object[] GetValues()
		{
			return new object[] {
				this._Serialnum,
				this._CreateTime,
				this._CreateSysUserSerialnum,
				this._UpdateTime,
				this._UpdateSysUserSerialnum,
				this._SysDepartmentSerialnum,
				this._Location,
				this._Lotitude,
				this._Latitude,
				this._SetupTime,
				this._UploadExperiod,
				this._Introduce,
				this._Sort,
				this._Remark};
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(IDataReader reader)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(reader["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(reader["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(reader["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(reader["UpdateSysUserSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(reader["SysDepartmentSerialnum"]);
			this._Location = DataUtils.ConvertValue<string>(reader["Location"]);
			this._Lotitude = DataUtils.ConvertValue<string>(reader["Lotitude"]);
			this._Latitude = DataUtils.ConvertValue<string>(reader["Latitude"]);
			this._SetupTime = DataUtils.ConvertValue<DateTime?>(reader["SetupTime"]);
			this._UploadExperiod = DataUtils.ConvertValue<int?>(reader["UploadExperiod"]);
			this._Introduce = DataUtils.ConvertValue<string>(reader["Introduce"]);
			this._Sort = DataUtils.ConvertValue<int>(reader["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(reader["Remark"]);
		}
		/// <summary>
		/// 给当前实体赋值
		/// </summary>
		public override void SetPropertyValues(DataRow row)
		{
			this._Serialnum = DataUtils.ConvertValue<string>(row["Serialnum"]);
			this._CreateTime = DataUtils.ConvertValue<DateTime>(row["CreateTime"]);
			this._CreateSysUserSerialnum = DataUtils.ConvertValue<string>(row["CreateSysUserSerialnum"]);
			this._UpdateTime = DataUtils.ConvertValue<DateTime>(row["UpdateTime"]);
			this._UpdateSysUserSerialnum = DataUtils.ConvertValue<string>(row["UpdateSysUserSerialnum"]);
			this._SysDepartmentSerialnum = DataUtils.ConvertValue<string>(row["SysDepartmentSerialnum"]);
			this._Location = DataUtils.ConvertValue<string>(row["Location"]);
			this._Lotitude = DataUtils.ConvertValue<string>(row["Lotitude"]);
			this._Latitude = DataUtils.ConvertValue<string>(row["Latitude"]);
			this._SetupTime = DataUtils.ConvertValue<DateTime?>(row["SetupTime"]);
			this._UploadExperiod = DataUtils.ConvertValue<int?>(row["UploadExperiod"]);
			this._Introduce = DataUtils.ConvertValue<string>(row["Introduce"]);
			this._Sort = DataUtils.ConvertValue<int>(row["Sort"]);
			this._Remark = DataUtils.ConvertValue<string>(row["Remark"]);
		}
		#endregion

		#region _Field
		/// <summary>
		/// 字段信息
		/// </summary>
		public class _
		{
			/// <summary>
			/// * 
			/// </summary>
			public readonly static Field All = new Field("*","WeatherStation");
			/// <summary>
			/// 编码
			/// </summary>
			public readonly static Field Serialnum = new Field("Serialnum","WeatherStation","编码");
			/// <summary>
			/// 创建时间
			/// </summary>
			public readonly static Field CreateTime = new Field("CreateTime","WeatherStation","创建时间");
			/// <summary>
			/// 创建用户
			/// </summary>
			public readonly static Field CreateSysUserSerialnum = new Field("CreateSysUserSerialnum","WeatherStation","创建用户");
			/// <summary>
			/// 更新时间
			/// </summary>
			public readonly static Field UpdateTime = new Field("UpdateTime","WeatherStation","更新时间");
			/// <summary>
			/// 更新用户
			/// </summary>
			public readonly static Field UpdateSysUserSerialnum = new Field("UpdateSysUserSerialnum","WeatherStation","更新用户");
			/// <summary>
			/// 机构编码
			/// </summary>
			public readonly static Field SysDepartmentSerialnum = new Field("SysDepartmentSerialnum","WeatherStation","机构编码");
			/// <summary>
			/// 安装位置
			/// </summary>
			public readonly static Field Location = new Field("Location","WeatherStation","安装位置");
			/// <summary>
			/// 经度
			/// </summary>
			public readonly static Field Lotitude = new Field("Lotitude","WeatherStation","经度");
			/// <summary>
			/// 纬度
			/// </summary>
			public readonly static Field Latitude = new Field("Latitude","WeatherStation","纬度");
			/// <summary>
			/// 安装时间
			/// </summary>
			public readonly static Field SetupTime = new Field("SetupTime","WeatherStation","安装时间");
			/// <summary>
			/// 数据上传频率（几分钟上传一次）
			/// </summary>
			public readonly static Field UploadExperiod = new Field("UploadExperiod","WeatherStation","数据上传频率（几分钟上传一次）");
			/// <summary>
			/// 介绍
			/// </summary>
			public readonly static Field Introduce = new Field("Introduce","WeatherStation","介绍");
			/// <summary>
			/// 排序
			/// </summary>
			public readonly static Field Sort = new Field("Sort","WeatherStation","排序");
			/// <summary>
			/// 备注
			/// </summary>
			public readonly static Field Remark = new Field("Remark","WeatherStation","备注");
		}
		#endregion


	}
}

