//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AhnqIot.AreaStationDataProcess.AHNQ.Weather {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AHNQ.Weather.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 StationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getForcast", ReplyAction="*")]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse getForcast(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getForcast", ReplyAction="*")]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse> getForcastAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 StationId 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeather", ReplyAction="*")]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse getWeather(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse> getWeatherAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 city 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeatherByCity", ReplyAction="*")]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse getWeatherByCity(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getWeatherByCity", ReplyAction="*")]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse> getWeatherByCityAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 areaName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarm", ReplyAction="*")]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse getAlarm(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAlarm", ReplyAction="*")]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse> getAlarmAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForcastRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getForcast", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequestBody Body;
        
        public getForcastRequest() {
        }
        
        public getForcastRequest(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getForcastRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StationId;
        
        public getForcastRequestBody() {
        }
        
        public getForcastRequestBody(string StationId) {
            this.StationId = StationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getForcastResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getForcastResponse", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponseBody Body;
        
        public getForcastResponse() {
        }
        
        public getForcastResponse(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getForcastResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getForcastResult;
        
        public getForcastResponseBody() {
        }
        
        public getForcastResponseBody(string getForcastResult) {
            this.getForcastResult = getForcastResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeather", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequestBody Body;
        
        public getWeatherRequest() {
        }
        
        public getWeatherRequest(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeatherRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string StationId;
        
        public getWeatherRequestBody() {
        }
        
        public getWeatherRequestBody(string StationId) {
            this.StationId = StationId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponseBody Body;
        
        public getWeatherResponse() {
        }
        
        public getWeatherResponse(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWeatherResult;
        
        public getWeatherResponseBody() {
        }
        
        public getWeatherResponseBody(string getWeatherResult) {
            this.getWeatherResult = getWeatherResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherByCityRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeatherByCity", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequestBody Body;
        
        public getWeatherByCityRequest() {
        }
        
        public getWeatherByCityRequest(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeatherByCityRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string city;
        
        public getWeatherByCityRequestBody() {
        }
        
        public getWeatherByCityRequestBody(string city) {
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWeatherByCityResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWeatherByCityResponse", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponseBody Body;
        
        public getWeatherByCityResponse() {
        }
        
        public getWeatherByCityResponse(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getWeatherByCityResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getWeatherByCityResult;
        
        public getWeatherByCityResponseBody() {
        }
        
        public getWeatherByCityResponseBody(string getWeatherByCityResult) {
            this.getWeatherByCityResult = getWeatherByCityResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlarmRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlarm", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequestBody Body;
        
        public getAlarmRequest() {
        }
        
        public getAlarmRequest(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlarmRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string areaName;
        
        public getAlarmRequestBody() {
        }
        
        public getAlarmRequestBody(string areaName) {
            this.areaName = areaName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAlarmResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAlarmResponse", Namespace="http://tempuri.org/", Order=0)]
        public AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponseBody Body;
        
        public getAlarmResponse() {
        }
        
        public getAlarmResponse(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAlarmResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getAlarmResult;
        
        public getAlarmResponseBody() {
        }
        
        public getAlarmResponseBody(string getAlarmResult) {
            this.getAlarmResult = getAlarmResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap>, AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getForcast(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest request) {
            return base.Channel.getForcast(request);
        }
        
        public string getForcast(string StationId) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequestBody();
            inValue.Body.StationId = StationId;
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse retVal = ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getForcast(inValue);
            return retVal.Body.getForcastResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse> AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getForcastAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest request) {
            return base.Channel.getForcastAsync(request);
        }
        
        public System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastResponse> getForcastAsync(string StationId) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getForcastRequestBody();
            inValue.Body.StationId = StationId;
            return ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getForcastAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getWeather(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest request) {
            return base.Channel.getWeather(request);
        }
        
        public string getWeather(string StationId) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequestBody();
            inValue.Body.StationId = StationId;
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse retVal = ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getWeather(inValue);
            return retVal.Body.getWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse> AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getWeatherAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest request) {
            return base.Channel.getWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherResponse> getWeatherAsync(string StationId) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherRequestBody();
            inValue.Body.StationId = StationId;
            return ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getWeatherAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getWeatherByCity(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest request) {
            return base.Channel.getWeatherByCity(request);
        }
        
        public string getWeatherByCity(string city) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequestBody();
            inValue.Body.city = city;
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse retVal = ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getWeatherByCity(inValue);
            return retVal.Body.getWeatherByCityResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse> AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getWeatherByCityAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest request) {
            return base.Channel.getWeatherByCityAsync(request);
        }
        
        public System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityResponse> getWeatherByCityAsync(string city) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getWeatherByCityRequestBody();
            inValue.Body.city = city;
            return ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getWeatherByCityAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getAlarm(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest request) {
            return base.Channel.getAlarm(request);
        }
        
        public string getAlarm(string areaName) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequestBody();
            inValue.Body.areaName = areaName;
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse retVal = ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getAlarm(inValue);
            return retVal.Body.getAlarmResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse> AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap.getAlarmAsync(AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest request) {
            return base.Channel.getAlarmAsync(request);
        }
        
        public System.Threading.Tasks.Task<AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmResponse> getAlarmAsync(string areaName) {
            AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest inValue = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequest();
            inValue.Body = new AhnqIot.AreaStationDataProcess.AHNQ.Weather.getAlarmRequestBody();
            inValue.Body.areaName = areaName;
            return ((AhnqIot.AreaStationDataProcess.AHNQ.Weather.WebServiceSoap)(this)).getAlarmAsync(inValue);
        }
    }
}
